// web/src/routes/account/profile/Sidebar.svelte
<script lang="ts">
  import RxImage from '$lib/components/RxImage.svelte'
  import RxTag from '$lib/components/RxTag.svelte'
  import { i18n } from '$lib/i18n'
  import { Permission, permissionToString, type User } from '$lib/models/user'

  export let loading: boolean = false
  export let user: User | null
</script>

<div class="w-full flex flex-col">
  <div class="h-28 flex flex-row items-center p-6 border-b border-b-base-content/5">
    <div class="rounded-full overflow-clip w-12 h-12 mx-2 ring-4 ring-offset-base-100 ring-offset-4">
      {#if user?.cover_path}
        <RxImage src={user?.cover_path} {loading}></RxImage>
      {:else}
        <div class="w-full h-full flex flex-col justify-center items-center">
          <span class="text-3xl font-bold">{user?.name.slice(0, 2)}</span>
        </div>
      {/if}
    </div>
    <div class="flex flex-col justify-center space-y-2 ml-6">
      <span class="font-bold text-xl">{user?.name}</span>
      <span class="font-bold text-base opacity-60">0x{user?.id.toString(16).padStart(6, '0')}</span>
    </div>
  </div>
  <div class="flex flex-col p-6">
    <h2 class="font-bold text-base opacity-60 flex flex-row space-x-2 items-center">
      <span class="icon-[fluent--mail-20-regular] w-5 h-5"></span>
      <span>
        {$i18n.t('account.email')}
      </span>
    </h2>
    <a class="hover:underline mt-2 px-2" href={`mailto:${user?.email}`}>{user?.email}</a>
    <h2 class="font-bold text-base opacity-60 flex flex-row space-x-2 items-center mt-6">
      <span class="icon-[fluent--shield-question-20-regular] w-5 h-5"></span>
      <span>
        {$i18n.t('account.status')}
      </span>
    </h2>
    <p class="mt-2 flex flex-row flex-wrap">
      {#if user?.banned}
        <RxTag class="m-1" label={$i18n.t('account.banned')} level="error"></RxTag>
      {/if}
      {#if user?.hidden}
        <RxTag class="m-1" label={$i18n.t('account.hidden')} level="warning"></RxTag>
      {/if}
      {#if !user?.banned && !user?.hidden}
        <RxTag class="m-1" label={$i18n.t('account.ok')} level="success"></RxTag>
      {/if}
    </p>
    <h2 class="font-bold text-base opacity-60 flex flex-row space-x-2 items-center mt-6">
      <span class="icon-[fluent--key-multiple-20-regular] w-5 h-5"></span>
      <span>
        {$i18n.t('account.permissions')}
      </span>
    </h2>
    <p class="mt-2 flex flex-wrap flex-row">
      {#each user?.permissions.filter((p) => p !== Permission.Basic) || [] as permission}
        <RxTag class="m-1" label={permissionToString(permission)}></RxTag>
      {/each}
    </p>
  </div>
</div>

// web/src/routes/users/[user]/_blocks/sidebar.tsx
import { mediaPath } from "@/lib/utils/media";
import Tag from "@/lib/widgets/tag";
import { type User, permissionToString } from "@models/user";
import { fullTheme, t } from "@storage/theme";
import Avatar from "@widgets/avatar";
import Divider from "@widgets/divider";
import { OverlayScrollbarsComponent } from "overlayscrollbars-solid";
import { For } from "solid-js";

export default function (props: { user: User | null; loading?: boolean }) {
  return (
    <div class="w-full h-full overflow-hidden">
      <OverlayScrollbarsComponent
        options={{
          scrollbars: {
            theme: `os-theme-${fullTheme()}`,
            autoHide: "scroll",
          },
        }}
        class="relative w-full h-full print:h-auto print:overflow-auto"
        defer
      >
        <div class="flex flex-col min-h-full space-y-2 p-3 lg:p-6">
          <div class="flex flex-row space-x-4 lg:space-x-6 p-2 lg:p-4 items-center">
            <Avatar
              class="w-12 h-12"
              src={(props.user?.avatar && mediaPath(props.user?.avatar)) || undefined}
              fallback={props.user?.nickname}
              loading={props.loading}
            />
            <div class="flex-1 flex flex-col space-y-1 justify-center">
              <h2 class="font-bold">{props.user?.nickname}</h2>
              <p class="opacity-60">
                <span>{props.user?.account}</span>
                <span>#</span>
                <span>{props.user?.id.toString(16).padStart(6, "0")}</span>
              </p>
            </div>
          </div>
          <Divider />
          <div class="flex flex-row space-x-2 items-center px-2 py-2">
            <span class="icon-[fluent--mail-20-regular] w-5 h-5" />
            <a
              class={`font-bold ${props.user?.email ? "hover:underline" : "blur pointer-events-none"}`.trim()}
              href={`mailto:${props.user?.email}`}
            >
              {props.user?.email ?? "fake.email@ret.sh.cn"}
            </a>
          </div>
          <Divider />
          <div class="flex flex-row space-x-2 items-center px-2 py-2">
            <span class="icon-[fluent--hat-graduation-20-regular] w-5 h-5" />
            <span class="font-bold">{props.user?.institute_name ?? t("user.noInstitute")}</span>
          </div>
          <Divider />
          <div class="flex flex-row flex-wrap">
            <For each={props.user?.permissions || []}>
              {(permission) => (
                <Tag level="info" class="m-1">
                  <span>{permissionToString(permission)}</span>
                </Tag>
              )}
            </For>
          </div>
          <div class="flex-1" />
          <div class="h-12 flex items-center justify-center">
            <span class="opacity-60">
              {t("user.registeredAt", { time: props.user?.registered_at.toFormat("yyyy-MM-dd") || "UNKNOWN" })}
            </span>
          </div>
        </div>
      </OverlayScrollbarsComponent>
    </div>
  );
}
