// web/src/routes/games/[game]/teams/[team]/Sidebar.svelte
<script lang="ts">
  import RxLink from '$lib/components/RxLink.svelte'
  import { i18n } from '$lib/i18n'
  import type { Team } from '$lib/models/team'
  import type { User } from '$lib/models/user'
  import RxImage from '$lib/components/RxImage.svelte'

  export let loading: boolean
  export let team: Team | null
  export let members: User[]
</script>

<div class="w-full flex flex-col">
  <div class="h-28 flex flex-row items-center p-6 border-b border-b-base-content/5">
    <div class="rounded-full overflow-clip w-12 h-12 mx-2 ring-4 ring-offset-base-100 ring-offset-4">
      <div class="w-full h-full flex flex-col justify-center items-center">
        <span class="text-3xl font-bold">{team?.name.slice(0, 1)}</span>
      </div>
    </div>
    <div class="flex flex-col justify-center space-y-2 ml-6">
      <span class="font-bold text-xl">{loading ? $i18n.t('account.loading') : team?.name}</span>
      <span class="font-bold text-base opacity-60">0x{team?.id.toString(16).padStart(6, '0')}</span>
    </div>
  </div>
  <div class="flex flex-col p-6 space-y-4">
    <h2 class="font-bold text-base opacity-60 flex flex-row space-x-2 items-center">
      <span class="icon-[fluent--person-20-regular] w-5 h-5"></span>
      <span>
        {$i18n.t('game.teamMembers')}
      </span>
    </h2>
    {#each members as item}
      <RxLink justify="start" class="h-16 flex flex-nowrap overflow-hidden" href={`/users/${item.id}`} ghost>
        <div class="avatar">
          <div
            class="w-10 rounded-full ring-2 ring-offset-base-100 ring-offset-2 !flex flex-col justify-center items-center"
          >
            {#if item.cover_path}
              <RxImage src={item.cover_path} loading={false} />
            {:else}
              <span class="w-5 h-5 icon-[fluent--person-20-regular]" />
            {/if}
          </div>
        </div>
        <div class="ml-2 flex flex-col items-start overflow-hidden">
          <span class="font-bold text-ellipsis overflow-hidden whitespace-nowrap w-full">{item.name}</span>
          <span class="opacity-60">0x{item.id.toString(16).padStart(6, '0')}</span>
        </div>
      </RxLink>
    {/each}
  </div>
</div>

// web/src/routes/games/[game]/teams/[team]/_blocks/sidebar.tsx
import { mediaPath } from "@lib/utils/media";
import type { Team } from "@models/team";
import type { User } from "@models/user";
import { A } from "@solidjs/router";
import { fullTheme, t } from "@storage/theme";
import Avatar from "@widgets/avatar";
import Divider from "@widgets/divider";
import LoadingTips from "@widgets/loading-tips";
import { OverlayScrollbarsComponent } from "overlayscrollbars-solid";
import { For, Show } from "solid-js";

export default function (props: {
  team: Team | null;
  members: User[];
  loading?: boolean;
}) {
  return (
    <div class="w-full h-full overflow-hidden">
      <OverlayScrollbarsComponent
        options={{
          scrollbars: {
            theme: `os-theme-${fullTheme()}`,
            autoHide: "scroll",
          },
        }}
        class="relative w-full h-full print:h-auto print:overflow-auto"
        defer
      >
        <div class="flex flex-col min-h-full space-y-2 p-3 lg:p-6">
          <div class="flex flex-row space-x-4 lg:space-x-6 p-2 lg:p-4 items-center">
            <span class="w-12 h-12 shrink-0 icon-[fluent--flag-20-regular]" />
            <div class="flex-1 flex flex-col space-y-1 justify-center overflow-hidden">
              <h2 class="font-bold w-full text-start truncate">{props.team?.name}</h2>
              <p class="opacity-60 w-full text-start truncate">
                <span class="text-primary">{props.team?.game_name}</span>
                <span>#</span>
                <span>{props.team?.id.toString(16).padStart(6, "0")}</span>
              </p>
            </div>
          </div>
          <Divider />
          <div class="flex flex-row space-x-2 items-center px-2 py-2">
            <span class="shrink-0 icon-[fluent--hat-graduation-20-regular] w-5 h-5" />
            <span class="font-bold">{props.team?.institute_name ?? t("institute.empty")}</span>
          </div>
          <Divider />
          <Show when={props.loading}>
            <div class="min-h-12 p-2 flex items-center space-x-2 overflow-hidden">
              <LoadingTips />
            </div>
            <Divider />
          </Show>
          <For each={props.members}>
            {(member) => (
              <>
                <A
                  class="px-2 py-2 flex items-center font-bold space-x-4 group cursor-pointer"
                  href={`/users/${member.id}`}
                >
                  <Avatar
                    class="w-6 h-6"
                    src={(member.avatar && mediaPath(member.avatar)) || undefined}
                    fallback={member.account || undefined}
                  />
                  <span class="flex-1 truncate text-start group-hover:underline">
                    <span>{member.nickname}</span>
                    <span class="font-normal px-2 opacity-60">
                      {member.account}#{member.id.toString(16).padStart(6, "0")}
                    </span>
                  </span>
                </A>
                <Divider />
              </>
            )}
          </For>
        </div>
      </OverlayScrollbarsComponent>
    </div>
  );
}
