// web/src/routes/admin/platform/media/+page.svelte
<script lang="ts">
  import { platform } from '$lib/stores/platform'
  import { i18n } from '$lib/i18n'
  import { z } from 'zod'
  import { validator } from '@felte/validator-zod'
  import { createForm } from 'felte'
  import RxInput from '$lib/components/RxInput.svelte'
  import RxForm from '$lib/components/RxForm.svelte'
  import RxFormItem from '$lib/components/RxFormItem.svelte'
  import RxButton from '$lib/components/RxButton.svelte'
  import RxCheckBox from '$lib/components/RxCheckBox.svelte'
  import { getPlatformConfig, setPlatformConfig } from '$lib/api/v1/platform'
  import { onMount } from 'svelte'
  import type { Obj } from '@felte/core'
  import type { Config } from '$lib/models/config'
  import { showMessage } from '$lib/stores/toast'
  import { user } from '$lib/stores/user'
  import type { AxiosError } from 'axios'
  import { blur } from 'svelte/transition'

  let schema = z.object({
    anti_theft: z.boolean(),
    limit: z.number().min(10, { message: $i18n.t('init.mediaLimitInvalid') }),
  })

  let loading = false
  let submitting = false
  let platformConfig: Config = {}
  const { form, data, errors } = createForm({
    extend: validator({ schema }),
    onSubmit(values) {
      submitting = true
      const payload: Config = {
        ...platformConfig,
        media: values,
      } as Config
      setPlatformConfig(payload, $user.token)
        .then(() => {
          showMessage('success', $i18n.t('admin.config.saved'), 5000)
        })
        .catch((error) => {
          showMessage('error', `${$i18n.t('admin.config.saveFailed')}: ${(error as AxiosError).response?.data}`, 5000)
        })
        .finally(() => {
          submitting = false
        })
    },
  })
  onMount(() => {
    loading = true
    getPlatformConfig()
      .then((res) => {
        platformConfig = res
        data.update(() => {
          return res.media as unknown as Obj
        })
      })
      .catch((error) => {
        showMessage(
          'error',
          `${$i18n.t('admin.config.platform.fetchFailed')}: ${(error as AxiosError).response?.data}`,
          5000
        )
      })
      .finally(() => {
        loading = false
      })
  })
</script>

<svelte:head><title>{$i18n.t('init.mediaSettings')} - {$platform.name}</title></svelte:head>
<div class="flex-1 relative">
  <div class="flex-1 flex flex-row p-4 lg:p-6 justify-center">
    <div class="flex-1 flex flex-col max-w-5xl">
      <div class="m-2 md:m-4 flex flex-row justify-center items-center space-x-6">
        <span class="icon-[fluent--chevron-double-right-20-regular] opacity-60" />
        <h1 class="text-2xl font-bold">{$i18n.t('init.mediaSettings')}</h1>
        <span class="icon-[fluent--chevron-double-left-20-regular] opacity-60" />
      </div>
      <RxForm {form}>
        <RxFormItem
          name="limit"
          label={$i18n.t('init.mediaLimit')}
          hasError={$errors.limit !== null}
          errors={$errors.limit}
        >
          <RxInput
            icon="icon-[fluent--code-20-regular]"
            class="w-full"
            id="limit"
            name="limit"
            hasError={$errors.limit !== null}
            placeholder={$i18n.t('init.mediaLimitPlaceholder')}
            value={platformConfig.media?.limit}
            type="number"
          />
        </RxFormItem>
        <RxFormItem name="anti_theft" label="" hasError={$errors.anti_theft !== null} errors={$errors.anti_theft}>
          <RxCheckBox
            id="anti_theft"
            name="anti_theft"
            checked={platformConfig.media?.anti_theft}
            label={$i18n.t('init.mediaAntiTheft')}
          />
        </RxFormItem>
        <RxFormItem name="submitAction" label="">
          <RxButton class="w-full" level="primary" type="submit" loading={submitting}>
            {submitting ? $i18n.t('admin.config.updating') : $i18n.t('admin.config.update')}
          </RxButton>
        </RxFormItem>
      </RxForm>
      <div class="h-32"></div>
    </div>
  </div>
  {#if loading}
    <div
      class="absolute top-0 left-0 w-full h-full z-20 backdrop-blur flex flex-row justify-center items-center"
      transition:blur={{ amount: 20, duration: 300 }}
    >
      <span class="loading loading-spinner loading-sm" />
    </div>
  {/if}
</div>

// web/src/routes/admin/media/index.tsx
import { getPlatformConfig, updatePlatformConfig } from "@api/platform";
import type { Config, MediaConfig } from "@models/config";
import { createForm, setValues } from "@modular-forms/solid";
import { Title } from "@storage/header";
import { platformStore } from "@storage/platform";
import { t } from "@storage/theme";
import { addToast } from "@storage/toast";
import Button from "@widgets/button";
import Checkbox from "@widgets/checkbox";
import Input from "@widgets/input";
import Slider from "@widgets/slider";
import type { HTTPError } from "ky";
import { createSignal, onMount } from "solid-js";

export default function () {
  const [form, { Form, Field }] = createForm<MediaConfig>();
  const [loading, setLoading] = createSignal(false);
  const [config, setConfig] = createSignal(null as null | Config);
  onMount(() => {
    getPlatformConfig().then((resp) => {
      setConfig(resp);
      setValues(form, {
        path: resp.media.path,
        limit: resp.media.limit,
        anti_theft: resp.media.anti_theft,
      });
    });
  });
  function onSubmit(result: MediaConfig) {
    setLoading(true);
    if (!config()) {
      addToast({
        level: "error",
        description: t("admin.platform.fetchNotReady")!,
        duration: 5000,
      });
      return;
    }
    const mergedConfig = {
      ...config(),
      media: result,
    } as Config;
    updatePlatformConfig(mergedConfig)
      .then(() => {
        setConfig(mergedConfig);
        addToast({
          level: "success",
          description: t("admin.platform.updateSuccess")!,
          duration: 5000,
        });
      })
      .catch((err: HTTPError) => {
        err.response.text().then((text) => {
          addToast({
            level: "error",
            description: `${t("admin.platform.updateFailed")}: ${text}`,
            duration: 5000,
          });
        });
      })
      .finally(() => setLoading(false));
  }
  return (
    <>
      <Title title={`${t("admin.media.title")} - ${platformStore.config.name || t("platform.name")}`} />
      <div class="flex-1 flex flex-col items-center">
        <Form onSubmit={onSubmit} class="w-full max-w-5xl p-3 lg:p-6 flex flex-col space-y-2">
          <h3 class="h-12 flex items-center border-b border-b-layer-content/10 font-bold space-x-2">
            <span class="icon-[fluent--settings-20-regular] w-5 h-5" />
            <span>{t("admin.media.title")}</span>
          </h3>
          <Field name="path">
            {(field, props) => (
              <Input
                class="flex-1"
                disabled
                title={t("admin.media.path")}
                placeholder={t("admin.media.path")}
                icon={<span class="icon-[fluent--server-link-20-regular] w-5 h-5" />}
                value={field.value}
                error={field.error}
                {...props}
              />
            )}
          </Field>
          <div class="flex flex-col space-y-2 lg:flex-row lg:space-y-0 lg:space-x-2 lg:items-end">
            <Field name="anti_theft" type="boolean">
              {(field, props) => (
                <Checkbox
                  inputProps={props}
                  title={t("admin.media.antiTheft")}
                  checked={field.value ?? false}
                  error={field.error}
                >
                  <span class="flex-1 text-start">{t("admin.media.antiTheft")}</span>
                </Checkbox>
              )}
            </Field>
            <Field name="limit" type="number">
              {(field, props) => (
                <Slider
                  class="flex-1"
                  label={t("admin.media.limit")!}
                  max={1000}
                  min={10}
                  step={10}
                  name={field.name}
                  value={[field.value || 1]}
                  inputProps={props}
                />
              )}
            </Field>
          </div>
          <Button type="submit" level="primary" class="!mt-4" loading={loading()} disabled={!config() || loading()}>
            {t("form.save")}
          </Button>
        </Form>
      </div>
    </>
  );
}
