// web/src/routes/admin/games/[game]/challenges/Hints.svelte
<script lang="ts">
  import { createHint, deleteHint, getChallengeHints } from '$lib/api/challenge'
  import RxButton from '$lib/components/RxButton.svelte'
  import RxInput from '$lib/components/RxInput.svelte'
  import { i18n } from '$lib/i18n'
  import type { Challenge } from '$lib/models/challenge'
  import type { Hint } from '$lib/models/hint'
  import { theme } from '$lib/stores/theme'
  import { showMessage } from '$lib/stores/toast'
  import type { AxiosError } from 'axios'
  import { OverlayScrollbarsComponent } from 'overlayscrollbars-svelte'
  import { onMount } from 'svelte'
  import { load } from '../../../../account/login/+page'

  export let challenge: Challenge
  let loading = false
  let hints: Hint[] = []
  let newHint: Hint = {
    id: 0,
    created_at: 0,
    challenge_id: 0,
    content: '',
  }

  function fetchHints() {
    loading = true
    getChallengeHints(challenge.id)
      .then((res) => {
        hints = res
        console.log(hints)
      })
      .catch((err) => {
        showMessage('error', `${$i18n.t('submissions.fetchFailed')}: ${(err as AxiosError).response?.data}`, 5000)
      })
      .finally(() => {
        loading = false
      })
  }

  function handleDeleteHint(item: Hint) {
    deleteHint(challenge.id, item.id)
      .then(() => {
        showMessage('success', $i18n.t('hint.deleteSuccess'), 5000)
        fetchHints()
      })
      .catch((err) => {
        showMessage('error', `${$i18n.t('hint.deleteFailed')}: ${(err as AxiosError).response?.data}`, 5000)
      })
  }

  function handleCreateHint() {
    createHint(challenge.id, newHint)
      .then(() => {
        showMessage('success', $i18n.t('hint.createSuccess'), 5000)
        newHint = {
          id: 0,
          created_at: 0,
          challenge_id: 0,
          content: '',
        }
        fetchHints()
      })
      .catch((err) => {
        showMessage('error', `${$i18n.t('hint.createFailed')}: ${(err as AxiosError).response?.data}`, 5000)
      })
  }

  onMount(() => {
    fetchHints()
  })
</script>

<div class="w-full flex flex-1 flex-col">
  <div class="p-12 flex flex-row">
    <div class="w-full h-full">
      <OverlayScrollbarsComponent
        options={{
          scrollbars: {
            theme: $theme.colorScheme === 'light' ? 'os-theme-dark' : 'os-theme-light',
            autoHide: 'scroll',
          },
        }}
        class="w-full h-full relative print:hidden"
        defer
      >
        <div class="flex flex-row space-x-2">
          <RxInput bind:value={newHint.content} class="w-full" placeholder={$i18n.t('hint.new')} />
          <RxButton ghost on:click={handleCreateHint}>
            <span class="icon-[fluent--add-20-regular] w-5 h-5 text-info"></span>
          </RxButton>
        </div>
        {#if hints.length === 0}
          <p class="w-full min-h-full flex-1 flex flex-row justify-center items-center font-bold opacity-60">
            {$i18n.t('challenges.noHint')}
          </p>
        {/if}
        <div class="h-4"></div>
        {#each hints as item}
          <div
            class="flex flex-row border-b border-b-base-content/5 h-16 items-center px-4 space-x-2 w-full hover:bg-base-content/5"
          >
            <span class="icon-[fluent--info-20-regular] w-5 h-5 text-info flex-shrink-0" />
            <div class="text-base overflow-hidden w-full">
              <span>{item.content}</span>
            </div>
            <RxButton
              size="sm"
              ghost
              on:click={() => {
                handleDeleteHint(item)
              }}
            >
              <span class="icon-[fluent--delete-20-regular] w-5 h-5 text-error"></span>
            </RxButton>
          </div>
        {/each}
      </OverlayScrollbarsComponent>
    </div>
  </div>
</div>

// web/src/lib/blocks/challenge/hints.tsx
import { createChallengeHint, deleteChallengeHint, getChallengeHint, getTeamExtras } from "@/lib/api/game";
import type { Challenge } from "@/lib/models/challenge";
import { addToast } from "@/lib/storage/toast";
import type { Extra } from "@models/extra";
import type { Hint } from "@models/hint";
import { Permission } from "@models/user";
import { createForm, required, setValue, setValues } from "@modular-forms/solid";
import { accountStore } from "@storage/account";
import { gameStore, isGameAdmin } from "@storage/game";
import { t } from "@storage/theme";
import Button from "@widgets/button";
import Card from "@widgets/card";
import Input from "@widgets/input";
import Popover from "@widgets/popover";
import type { HTTPError } from "ky";
import { LoremIpsum } from "lorem-ipsum";
import { DateTime } from "luxon";
import { For, Show, createEffect, createSignal, untrack } from "solid-js";

type CreateHintForm = {
  content: string;
  cost: number;
};

export default function (props: { challenge?: Challenge }) {
  const [hints, setHints] = createSignal([] as Hint[]);
  const [extras, setExtras] = createSignal([] as Extra[]);
  const lorem = new LoremIpsum({
    wordsPerSentence: {
      max: 8,
      min: 3,
    },
  });
  const [form, { Form, Field }] = createForm<CreateHintForm>();
  setValue(form, "cost", 0);
  const [loading, setLoading] = createSignal(false);
  function onSubmit(result: CreateHintForm) {
    const hint = {
      id: 0,
      created_at: DateTime.now(),
      challenge_id: props.challenge!.id,
      content: result.content,
      cost: result.cost || 0,
    } as Hint;
    createChallengeHint(props.challenge!.game_id, props.challenge!.id, hint)
      .then(() => {
        addToast({
          level: "success",
          description: t("form.createSuccess")!,
          duration: 5000,
        });
        refreshHint();
        setValues(form, {
          content: undefined,
          cost: undefined,
        });
      })
      .catch((e: HTTPError) => {
        e.response.text().then((text) => {
          addToast({
            level: "error",
            description: `${t("form.createFailed")}: ${text}`,
            duration: 5000,
          });
        });
      });
  }
  function refreshHint() {
    setLoading(true);
    getChallengeHint(props.challenge!.game_id, props.challenge!.id)
      .then((resp) => {
        setHints(resp);
      })
      .catch((e: HTTPError) => {
        e.response.text().then((text) => {
          addToast({
            level: "error",
            description: `${t("game.challenge.fetchHintFailed")}: ${text}`,
            duration: 5000,
          });
        });
      })
      .finally(() => {
        setLoading(false);
      });
  }
  createEffect(() => {
    if (props.challenge) {
      untrack(() => {
        refreshHint();
        if (!isGameAdmin()) {
          getTeamExtras(gameStore.current!.id, gameStore.team!.id)
            .then((resp) => {
              setExtras(resp);
            })
            .catch((e: HTTPError) => {
              e.response.text().then((text) => {
                addToast({
                  level: "error",
                  description: `${t("game.challenge.fetchHintFailed")}: ${text}`,
                  duration: 5000,
                });
              });
            });
        }
      });
    }
  });

  function handleDeleteHint(id: number) {
    deleteChallengeHint(gameStore.current!.id, props.challenge!.id, id)
      .then(() => {
        refreshHint();
      })
      .catch((e: HTTPError) => {
        e.response.text().then((text) => {
          addToast({
            level: "error",
            description: `${t("form.deleteFailed")}: ${text}`,
          });
        });
      });
  }
  return (
    <div class="flex flex-col p-3 lg:p-6">
      <For each={hints()}>
        {(hint) => (
          <div class="px-2 min-h-12 py-1 border-b border-b-layer-content/10 flex items-center space-x-2">
            <span class="icon-[fluent--info-20-regular] w-5 h-5 text-primary flex-shrink-0" />
            <Show
              when={isGameAdmin() || hint.cost === 0 || extras().find((e) => e.hint_id === hint.id)}
              fallback={
                <>
                  <span class="blur pointer-events-none select-none flex-1">{lorem.generateSentences(1)}</span>
                  <Popover
                    size="sm"
                    ghost
                    btnContent={
                      <>
                        <span class="text-warning">-{hint.cost}</span>
                        <span class="opacity-60 text-warning">pts</span>
                        <span class="icon-[fluent--lock-20-regular] w-5 h-5 text-warning" />
                      </>
                    }
                  >
                    <Card contentClass="p-2 flex flex-row items-center">
                      <span class="px-2">
                        {t("game.challenge.confirmUnlockHint", {
                          cost: hint.cost,
                        })}
                      </span>
                      <Button size="sm" level="error">
                        {t("platform.yes")}
                      </Button>
                    </Card>
                  </Popover>
                </>
              }
            >
              <span class="flex-1 text-start">{hint.content}</span>
              <Show when={hint.cost > 0}>
                <span class="text-success">-{hint.cost}</span>
                <span class="opacity-60 text-success">pts</span>
                <span class="icon-[fluent--lock-open-20-regular] w-5 h-5 text-success" />
              </Show>
            </Show>
            <Show when={isGameAdmin()}>
              <Button
                size="sm"
                ghost
                square
                onClick={() => {
                  handleDeleteHint(hint.id);
                }}
              >
                <span class="icon-[fluent--delete-20-regular] w-5 h-5" />
              </Button>
            </Show>
          </div>
        )}
      </For>
      <Show
        when={
          accountStore.permissions.includes(Permission.Game) && gameStore.current?.admins.includes(accountStore.id!)
        }
      >
        <Form onSubmit={onSubmit} class="px-2 min-h-12 border-b border-b-layer-content/10 flex items-center space-x-2">
          <span class="icon-[fluent--info-20-regular] w-5 h-5 text-primary flex-shrink-0" />
          <Field name="content" validate={[required(t("game.challenge.hintRequired")!)]}>
            {(field, props) => (
              <Input
                type="text"
                value={field.value}
                error={field.error}
                {...props}
                required
                noLabel
                placeholder={t("game.challenge.createHint")}
                class="flex-1"
                size="sm"
              />
            )}
          </Field>
          <Field name="cost" type="number">
            {(field, props) => (
              <Input
                type="number"
                value={field.value}
                error={field.error}
                {...props}
                noLabel
                placeholder={t("game.challenge.createHintCost")}
                class="w-24"
                size="sm"
              />
            )}
          </Field>
          <span class="font-bold opacity-60">pts</span>
          <span class="w-8" />
          <Button size="sm" level="primary" type="submit" loading={loading()} disabled={loading()}>
            <span class="icon-[fluent--add-20-regular] w-5 h-5" />
            <span>{t("form.create")}</span>
          </Button>
        </Form>
      </Show>
    </div>
  );
}
