// web/src/routes/admin/cluster/index.tsx
import { type ClusterNode, getClusterConfig, getClusterNodes } from "@api/cluster";
import Spin from "@assets/animates/spin";
import { Title } from "@storage/header";
import { platformStore } from "@storage/platform";
import { t } from "@storage/theme";
import { addToast } from "@storage/toast";
import Button from "@widgets/button";
import Divider from "@widgets/divider";
import LoadingTips from "@widgets/loading-tips";
import type { HTTPError } from "ky";
import { DateTime } from "luxon";
import { For, Match, Show, Switch, createSignal } from "solid-js";

export default function () {
  const [available, setAvailable] = createSignal(false);
  const [loading, setLoading] = createSignal(true);
  const [since, setSince] = createSignal("");
  const [clusterDNS, setClusterDNS] = createSignal("");
  const [clusterDomain, setClusterDomain] = createSignal("");
  const [clusterNodes, setClusterNodes] = createSignal([] as ClusterNode[]);
  getClusterConfig()
    .then((resp) => {
      setAvailable(true);
      for (const c of resp.items) {
        if (c.data?.since) {
          setSince(c.data.since);
        }
        if (c.data?.clusterDNS) {
          setClusterDNS(c.data.clusterDNS);
        }
        if (c.data?.clusterDomain) {
          setClusterDomain(c.data.clusterDomain);
        }
      }
    })
    .catch(() => {
      setAvailable(false);
    })
    .finally(() => {
      setLoading(false);
    });
  getClusterNodes()
    .then((resp) => {
      setClusterNodes(resp.items);
    })
    .catch((err: HTTPError) => {
      void err.response.text().then((text) => {
        addToast({
          level: "error",
          description: `${t("admin.cluster.failedToFetchNodes")}: ${text}`,
          duration: 5000,
        });
      });
    });

  const [shownNode, setShownNode] = createSignal(null as ClusterNode | null);
  return (
    <>
      <Title title={`${t("admin.cluster.title")} - ${platformStore.config.name || t("platform.name")}`} />
      <div class="flex-1 flex flex-col p-3 lg:p-6">
        <div class="h-32 lg:h-48 flex flex-row items-center">
          <div class="h-full aspect-square flex items-center justify-center">
            <Switch>
              <Match when={loading()}>
                <Spin width={24} height={24} />
              </Match>
              <Match when={available()}>
                <span class="icon-[meteocons--compass] w-full h-full" />
              </Match>
              <Match when={true}>
                <span class="icon-[meteocons--code-red-fill] w-full h-full" />
              </Match>
            </Switch>
          </div>
          <h1 class="flex flex-col justify-center space-y-2">
            <span class="text-3xl lg:text-5xl font-bold">{t("admin.cluster.title")}</span>
            <Switch>
              <Match when={loading()}>
                <LoadingTips />
              </Match>
              <Match when={available()}>
                <span class="text-info">{t("admin.cluster.available")}</span>
              </Match>
              <Match when={true}>
                <span class="text-warning">{t("admin.cluster.unavailable")}</span>
              </Match>
            </Switch>
          </h1>
        </div>
        <Divider />
        <Show when={loading()}>
          <div class="h-20 lg:h-12 flex flex-row space-x-4 items-center px-4">
            <LoadingTips />
          </div>
          <Divider />
        </Show>
        <Show when={available()}>
          <div class="h-20 lg:h-12 flex flex-col lg:flex-row space-y-2 lg:space-y-0 lg:space-x-4 justify-center items-center px-3">
            <span class="lg:flex-1 opacity-60">
              Since {since()}, {DateTime.fromFormat(since(), "yyyy-MM-dd").diffNow().negate().toFormat("hh")} hours
              online
            </span>
            <span class="flex flex-row items-center space-x-4">
              <span>{clusterDomain()}</span>
              <span class="icon-[fluent--chevron-double-right-20-regular] w-5 h-5 opacity-60" />
              <span class="text-warning">{clusterDNS()}</span>
            </span>
          </div>
          <Divider />
          <div class="flex flex-row flex-wrap py-2">
            <For each={clusterNodes()}>
              {(node) => (
                <Button
                  class="m-1 min-w-fit !h-auto py-2"
                  level={shownNode()?.metadata.name === node.metadata.name ? "primary" : undefined}
                  onClick={() => setShownNode(node)}
                >
                  <span
                    class={`${
                      node.metadata.labels["node-role.kubernetes.io/master"] === "true"
                        ? "icon-[fluent--brain-circuit-20-regular]"
                        : "icon-[fluent--production-20-regular]"
                    } w-8 h-8 ${
                      shownNode()?.metadata.name === node.metadata.name ? "text-primary-content" : "text-success"
                    }`}
                  />
                  <div class="flex flex-col justify-center items-start min-w-fit">
                    <span class="font-bold">{node.metadata.name}</span>
                    <span class="opacity-60">{node.metadata.creationTimestamp}</span>
                  </div>
                </Button>
              )}
            </For>
          </div>
          <Divider />
          <Show
            when={shownNode()}
            fallback={
              <div class="flex-1 flex flex-col items-center justify-center space-y-8 opacity-60">
                <span class="icon-[fluent--organization-20-regular] w-24 h-24" />
                <span>{t("admin.cluster.selectNode")}</span>
              </div>
            }
          >
            <div class="h-12 flex flex-row items-center space-x-2 px-3">
              <span class="icon-[fluent--organization-20-regular] w-5 h-5" />
              <span class="font-bold flex-1 text-start">{shownNode()?.metadata.name}</span>
              <span class="opacity-60 hidden lg:inline">
                <span>Online at: </span>
                <span>{DateTime.fromISO(shownNode()!.metadata.creationTimestamp).toFormat("yyyy-MM-dd HH:mm:ss")}</span>
              </span>
              <Button size="sm" square title={t("admin.cluster.refreshNode")}>
                <span class="icon-[fluent--arrow-clockwise-20-regular] w-5 h-5" />
              </Button>
              <Button size="sm" square title={t("admin.cluster.updateNode")}>
                <span class="icon-[fluent--arrow-circle-up-20-regular] w-5 h-5" />
              </Button>
              <Button size="sm" square level="error" title={t("admin.cluster.disconnectNode")}>
                <span class="icon-[fluent--stop-20-regular] w-5 h-5" />
              </Button>
            </div>
            <Divider />
            <div class="p-3 lg:p-6 flex flex-col">
              <h3 class="text-center font-bold">{t("admin.cluster.nodeInfo")}</h3>
              <table>
                <tbody>
                  <For each={Object.entries(shownNode()!.status.nodeInfo)}>
                    {([key, value]) => (
                      <tr class="border-b border-b-layer-content/10">
                        <td class="font-bold opacity-60 p-2">{`${
                          /* @ts-expect-error key is dynamic */
                          t(`admin.cluster.data.nodeInfo.${key}`) as string
                        }`}</td>
                        <td class="p-2">{value}</td>
                      </tr>
                    )}
                  </For>
                  <tr class="border-b border-b-layer-content/10">
                    <td class="font-bold opacity-60 p-2">Provider ID</td>
                    <td class="p-2">{shownNode()?.spec.providerID}</td>
                  </tr>
                  <tr class="border-b border-b-layer-content/10">
                    <td class="font-bold opacity-60 p-2">Addresses</td>
                    <td class="p-2">
                      {shownNode()
                        ?.status.addresses.map((a) => a.address)
                        .join(", ")}
                    </td>
                  </tr>
                  <tr class="border-b border-b-layer-content/10">
                    <td class="font-bold opacity-60 p-2">Pod CIDRs</td>
                    <td class="p-2">{shownNode()?.spec.podCIDRs.join(", ")}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="flex flex-col">
              <h3 class="text-center font-bold">{t("admin.cluster.nodeResources")}</h3>
              <div class="flex flex-col xl:flex-row p-3 lg:p-6">
                <table class="flex-1">
                  <tbody>
                    <For each={Object.entries(shownNode()!.status.capacity)}>
                      {([key, value]) => (
                        <tr class="border-b border-b-layer-content/10">
                          <td class="font-bold opacity-60 p-2">Capacity {key}</td>
                          <td class="p-2">{value}</td>
                        </tr>
                      )}
                    </For>
                  </tbody>
                </table>
                <table class="flex-1">
                  <tbody>
                    <For each={Object.entries(shownNode()!.status.allocatable)}>
                      {([key, value]) => (
                        <tr class="border-b border-b-layer-content/10">
                          <td class="font-bold opacity-60 p-2">Allocatable {key}</td>
                          <td class="p-2">{value}</td>
                        </tr>
                      )}
                    </For>
                  </tbody>
                </table>
              </div>
            </div>
          </Show>
        </Show>
      </div>
    </>
  );
}

// web/src/routes/admin/statistics/cluster/+page.svelte
<script lang="ts">
  import { getPlatformClusterInfo } from '$lib/api/v1/platform'
  import { i18n } from '$lib/i18n'
  import type { ClusterInfo } from '$lib/models/config'
  import { showMessage } from '$lib/stores/toast'
  import type { AxiosError } from 'axios'
  import { onMount } from 'svelte'
  import Engine from '$lib/assets/animates/engine.svelte'
  import Compass from '$lib/assets/animates/compass.svelte'
  import KubenertesLogo from '$lib/assets/brands/kubernetes.svelte'
  import RxTag from '$lib/components/RxTag.svelte'
  import RxPopup from '$lib/components/RxPopup.svelte'
  import '$lib/styles/transitions.scss'
  import { blur } from 'svelte/transition'
  import { platform } from '$lib/stores/platform'

  let clusterInfo: ClusterInfo | null = null
  let loading = true
  let working = false

  onMount(() => {
    getPlatformClusterInfo()
      .then((resp) => {
        clusterInfo = resp
        working = true
      })
      .catch((err) => {
        showMessage('error', `${$i18n.t('platform.fetchStatFailed')}: ${(err as AxiosError).response?.data}`, 5000)
        working = false
      })
      .finally(() => {
        loading = false
      })
  })

  $: since = clusterInfo?.configs.items.find((item) => item.data?.since !== undefined)?.data?.since
  $: clusterDNS = clusterInfo?.configs.items.find((item) => item.data?.clusterDNS !== undefined)?.data?.clusterDNS
  $: clusterDomain = clusterInfo?.configs.items.find((item) => item.data?.clusterDomain !== undefined)?.data
    ?.clusterDomain
</script>

<svelte:head><title>{$i18n.t('admin.routes.cluster')} - {$platform.name}</title></svelte:head>
<div class="flex-1 flex flex-col p-6 space-y-2 relative">
  {#if !loading}
    <h1 class="text-3xl font-bold flex flex-row space-x-4 items-center">
      {#if working}
        <KubenertesLogo class="animate-helm" level="active" width={96} height={96} />
      {:else}
        <KubenertesLogo level="down" width={96} height={96} />
      {/if}
      <div class="flex flex-col space-y-2">
        {#if working}
          <span>
            <span>Kubernetes v{clusterInfo?.version.major}.{clusterInfo?.version.minor}</span>
            <span class="opacity-40">@</span>
            <span class="opacity-80">{clusterInfo?.default_namespace}</span>
          </span>
          <div class="text-base flex flex-row flex-wrap opacity-60">
            <span>
              Version: {clusterInfo?.version.gitVersion}-{clusterInfo?.version.goVersion}-{clusterInfo?.version
                .platform}
            </span>
          </div>
        {:else}
          <span>{$i18n.t('platform.clusterIsDown')}</span>
        {/if}
      </div>
      <div class="flex-1"></div>
      <Compass width={128} height={128} />
    </h1>
  {/if}
  <div class="divider"></div>
  <h2 class="font-bold text-base">{$i18n.t('admin.cluster.basicInfo')}</h2>
  <div class="flex flex-row space-x-6 items-center">
    <span>{$i18n.t('admin.cluster.since')}: {since}</span>
    <span class="flex-1"></span>
    <span>{$i18n.t('admin.cluster.clusterDNS')}: {clusterDNS}</span>
    <span>{$i18n.t('admin.cluster.clusterDomain')}: {clusterDomain}</span>
  </div>
  <div class="divider"></div>
  <h2 class="font-bold text-base">{$i18n.t('admin.cluster.activeNodes')}</h2>
  <div class="flex flex-row flex-wrap">
    {#if clusterInfo?.nodes.items}
      {#each clusterInfo.nodes.items as item}
        <RxPopup
          name={item.metadata.name}
          popupWidth="auto"
          placement="bottom-start"
          class="h-auto w-auto bg-neutral/40 border-base-content/5 backdrop-blur m-2 p-2"
          event="click-blur"
        >
          <div slot="button" class="flex flex-row space-x-2 p-2 items-center">
            <div class="text-success"><Engine width={64} height={64} /></div>
            <div class="flex flex-col font-normal justify-center space-y-2">
              <h2 class="font-bold text-start text-lg">{item.metadata.name}</h2>
              <p class="normal-case opacity-60">{item.status.nodeInfo.osImage}</p>
            </div>
          </div>
          <div class="p-6 rounded-box bg-neutral">
            <div class="flex flex-row items-center p-2 space-x-2 border-b border-b-base-content/5">
              <div class="h-2 w-2 bg-success rounded-full"></div>
              <h2 class="font-bold">{item.metadata.name}</h2>
              <div class="flex-1"></div>
              <div class="opacity-60">{item.metadata.uid}</div>
            </div>
            <div class="flex flex-row flex-wrap p-2">
              <RxTag
                class="m-1"
                label={`${item.status.nodeInfo.operatingSystem}-${item.status.nodeInfo.kernelVersion}`}
              />
              <RxTag class="m-1" label={item.status.nodeInfo.architecture} />
              <RxTag class="m-1" label={item.status.nodeInfo.osImage} />
            </div>
            <table class="table-auto table table-sm">
              {#each item.status.addresses as address}
                <tr>
                  <td class="font-bold opacity-60">{address.type}</td>
                  <td>{address.address}</td>
                </tr>
              {/each}
              <tr>
                <td class="font-bold opacity-60">Pod CIDR</td>
                <td>{item.spec.podCIDR}</td>
                <td class="font-bold opacity-60">Provider ID</td>
                <td>{item.spec.providerID}</td>
              </tr>
              <tr>
                <td class="font-bold opacity-60">Boot ID</td>
                <td>{item.status.nodeInfo.bootID}</td>
                <td class="font-bold opacity-60">Machine ID</td>
                <td>{item.status.nodeInfo.machineID}</td>
              </tr>
              <tr>
                <td class="font-bold opacity-60">Kubelet</td>
                <td>{item.status.nodeInfo.kubeletVersion}</td>
                <td class="font-bold opacity-60">Kube Proxy</td>
                <td>{item.status.nodeInfo.kubeProxyVersion}</td>
              </tr>
              <tr>
                <td class="font-bold opacity-60">Container Runtime</td>
                <td>{item.status.nodeInfo.containerRuntimeVersion}</td>
              </tr>
              <tr>
                <td class="font-bold opacity-60">CPU Allocatable</td>
                <td>{item.status.allocatable.cpu}</td>
                <td class="font-bold opacity-60">CPU Capacity</td>
                <td>{item.status.capacity.cpu}</td>
              </tr>
              <tr>
                <td class="font-bold opacity-60">Memory Allocatable</td>
                <td>{item.status.allocatable.memory}</td>
                <td class="font-bold opacity-60">Memory Capacity</td>
                <td>{item.status.capacity.memory}</td>
              </tr>
              <tr>
                <td class="font-bold opacity-60">Pods Allocatable</td>
                <td>{item.status.allocatable.pods}</td>
                <td class="font-bold opacity-60">Pods Capacity</td>
                <td>{item.status.capacity.pods}</td>
              </tr>
            </table>
          </div>
        </RxPopup>
      {/each}
    {/if}
  </div>
  {#if loading}
    <div
      class="absolute top-0 left-0 w-full h-full z-20 backdrop-blur flex flex-row justify-center items-center"
      transition:blur={{ amount: 20, duration: 300 }}
    >
      <span class="loading loading-spinner loading-sm" />
    </div>
  {/if}
</div>
