// web/src/routes/games/[game]/teams/[team]/_blocks/sidebar.tsx
import { mediaPath } from "@lib/utils/media";
import type { Team } from "@models/team";
import type { User } from "@models/user";
import { A } from "@solidjs/router";
import { fullTheme, t } from "@storage/theme";
import Avatar from "@widgets/avatar";
import Divider from "@widgets/divider";
import LoadingTips from "@widgets/loading-tips";
import { OverlayScrollbarsComponent } from "overlayscrollbars-solid";
import { For, Show } from "solid-js";

export default function (props: {
  team: Team | null;
  members: User[];
  loading?: boolean;
}) {
  return (
    <div class="w-full h-full overflow-hidden">
      <OverlayScrollbarsComponent
        options={{
          scrollbars: {
            theme: `os-theme-${fullTheme()}`,
            autoHide: "scroll",
          },
        }}
        class="relative w-full h-full print:h-auto print:overflow-auto"
        defer
      >
        <div class="flex flex-col min-h-full space-y-2 p-3 lg:p-6">
          <div class="flex flex-row space-x-4 lg:space-x-6 p-2 lg:p-4 items-center">
            <span class="w-12 h-12 shrink-0 icon-[fluent--flag-20-regular]" />
            <div class="flex-1 flex flex-col space-y-1 justify-center overflow-hidden">
              <h2 class="font-bold w-full text-start truncate">{props.team?.name}</h2>
              <p class="opacity-60 w-full text-start truncate">
                <span class="text-primary">{props.team?.game_name}</span>
                <span>#</span>
                <span>{props.team?.id.toString(16).padStart(6, "0")}</span>
              </p>
            </div>
          </div>
          <Divider />
          <div class="flex flex-row space-x-2 items-center px-2 py-2">
            <span class="shrink-0 icon-[fluent--hat-graduation-20-regular] w-5 h-5" />
            <span class="font-bold">{props.team?.institute_name ?? t("institute.empty")}</span>
          </div>
          <Divider />
          <Show when={props.loading}>
            <div class="min-h-12 p-2 flex items-center space-x-2 overflow-hidden">
              <LoadingTips />
            </div>
            <Divider />
          </Show>
          <For each={props.members}>
            {(member) => (
              <>
                <A
                  class="px-2 py-2 flex items-center font-bold space-x-4 group cursor-pointer"
                  href={`/users/${member.id}`}
                >
                  <Avatar
                    class="w-6 h-6"
                    src={(member.avatar && mediaPath(member.avatar)) || undefined}
                    fallback={member.account || undefined}
                  />
                  <span class="flex-1 truncate text-start group-hover:underline">
                    <span>{member.nickname}</span>
                    <span class="font-normal px-2 opacity-60">
                      {member.account}#{member.id.toString(16).padStart(6, "0")}
                    </span>
                  </span>
                </A>
                <Divider />
              </>
            )}
          </For>
        </div>
      </OverlayScrollbarsComponent>
    </div>
  );
}

// web/src/routes/wiki/Sidebar.svelte
<script lang="ts">
  import { getWikiList } from '$lib/api/wiki'
  import RxTree from '$lib/components/RxTree.svelte'
  import { i18n } from '$lib/i18n'
  import { transformToWikiEntry, type WikiEntry } from '$lib/models/wiki'
  import { theme } from '$lib/stores/theme'
  import { OverlayScrollbarsComponent } from 'overlayscrollbars-svelte'

  export let wiki: WikiEntry[]
  export let activeChains: number[] = []
  export let loading: boolean

  async function fetchChildren(id: number) {
    return transformToWikiEntry(await getWikiList(id))
  }
</script>

<OverlayScrollbarsComponent
  options={{
    scrollbars: { theme: $theme.colorScheme === 'light' ? 'os-theme-dark' : 'os-theme-light', autoHide: 'scroll' },
  }}
  class="w-full h-full flex flex-col relative print:hidden"
  defer
>
  <h1
    class="h-16 bg-base-100 border-b border-b-base-content/5 flex flex-row items-center justify-center space-x-2 p-4 font-bold sticky top-0 z-10"
  >
    <span class="w-6 h-6 icon-[fluent--hat-graduation-16-regular]" />
    <span>
      {$i18n.t('wiki.sideToc')}
    </span>
  </h1>
  {#if loading}
    <div class="flex flex-row justify-center items-center h-16 space-x-2">
      <span class="loading loading-spinner loading-sm" />
      <span class="text-base">{$i18n.t('wiki.fetchingList')}</span>
    </div>
  {:else}
    {#if wiki.length === 0}
      <p class="text-base font-semibold p-4 opacity-60 text-center">{$i18n.t('playground.emptyCategory')}</p>
    {/if}
    <div class="p-4">
      <RxTree bind:tree={wiki} {activeChains} addrPrefix="/wiki" {fetchChildren} />
    </div>
  {/if}
</OverlayScrollbarsComponent>
