// web/src/routes/admin/email/index.tsx
import Button from "@/lib/widgets/button";
import Checkbox from "@/lib/widgets/checkbox";
import Divider from "@widgets/divider";
import Editor from "@widgets/editor";
import Input from "@widgets/input";
import Select from "@widgets/select";
import { getPlatformConfig, updatePlatformConfig } from "@api/platform";
import type { Config, EmailConfig } from "@models/config";
import { createForm, custom, getValue, setValue, setValues } from "@modular-forms/solid";
import { Title } from "@storage/header";
import { platformStore } from "@storage/platform";
import { t } from "@storage/theme";
import { createSignal, onMount } from "solid-js";
import { addToast } from "@/lib/storage/toast";
import type { HTTPError } from "ky";

export default function () {
  const [form, { Form, Field }] = createForm<EmailConfig>();
  const [loading, setLoading] = createSignal(false);
  const [config, setConfig] = createSignal(null as null | Config);
  onMount(() => {
    getPlatformConfig().then((resp) => {
      setConfig(resp);
      setValues(form, {
        ...resp.email,
      });
    });
  });

  function onSubmit(result: EmailConfig) {
    setLoading(true);
    updatePlatformConfig({
      ...config()!,
      email: {
        ...config()?.email,
        ...result,
      },
    })
      .then(() => {
        addToast({
          level: "success",
          description: t("form.saveSuccess")!,
          duration: 5000,
        });
      })
      .catch((err: HTTPError) => {
        err.response.text().then((text) => {
          addToast({
            level: "error",
            description: `${t("form.saveFailed")}: ${text}`,
            duration: 5000,
          });
        });
      })
      .finally(() => {
        setLoading(false);
      });
  }

  return (
    <>
      <Title title={`${t("admin.email.title")} - ${platformStore.config.name || t("platform.name")}`} />
      <div class="flex-1 flex flex-col items-center">
        <Form onSubmit={onSubmit} class="w-full max-w-5xl p-3 lg:p-6 flex flex-col space-y-2">
          <h3 class="h-12 flex items-center border-b border-b-layer-content/10 font-bold space-x-2">
            <span class="icon-[fluent--mail-20-regular] w-5 h-5" />
            <span>{t("admin.email.title")}</span>
          </h3>
          <Field name="enabled" type="boolean">
            {(field, props) => (
              <Checkbox
                inputProps={props}
                title={t("admin.email.enabled")}
                checked={field.value ?? false}
                error={field.error}
              >
                <span class="flex-1 text-start">{t("admin.email.enabled")}</span>
              </Checkbox>
            )}
          </Field>

          <div class="flex flex-row space-x-2">
            <Field
              name="tls"
              validate={[
                custom((value) => {
                  if (!value && getValue(form, "enabled")) {
                    return false;
                  }
                  return true;
                }, t("admin.email.tlsRequired")!),
              ]}
            >
              {(field, props) => (
                <Select
                  name={field.name}
                  label={t("admin.email.tls")!}
                  disabled={getValue(form, "enabled") === false}
                  class="flex-1 max-w-64"
                  error={field.error}
                  placeholder={t("admin.email.tlsRequired")}
                  items={[
                    {
                      value: "none",
                      label: "None",
                      icon: "icon-[fluent--emoji-sad-20-regular]",
                    },
                    {
                      value: "tls",
                      label: "TLS",
                      icon: "icon-[fluent--lock-20-regular]",
                    },
                    {
                      value: "starttls",
                      label: "StartTLS",
                      icon: "icon-[fluent--lock-20-regular]",
                    },
                  ]}
                  value={field.value ? [field.value as string] : undefined}
                  inputProps={props}
                  onValueChange={(e) => {
                    setValue(form, "tls", e.value.at(0) as "none" | "tls" | "starttls");
                  }}
                >
                  {/* TODO: integrate with modular-forms */}
                </Select>
              )}
            </Field>
            <Field
              name="host"
              validate={[
                custom((value) => {
                  if (!value && getValue(form, "enabled")) {
                    return false;
                  }
                  return true;
                }, t("admin.email.hostRequired")!),
              ]}
            >
              {(field, props) => (
                <Input
                  class="flex-1"
                  disabled={getValue(form, "enabled") === false}
                  title={t("admin.email.host")}
                  placeholder={t("admin.email.host")}
                  icon={<span class="icon-[fluent--server-link-20-regular] w-5 h-5" />}
                  value={field.value}
                  error={field.error}
                  {...props}
                />
              )}
            </Field>
            <Field
              name="port"
              type="number"
              validate={[
                custom((value) => {
                  if (!value && getValue(form, "port")) {
                    return false;
                  }
                  return true;
                }, t("admin.email.portRequired")!),
                custom((value) => {
                  if (value && (value < 1 || value > 65535)) {
                    return false;
                  }
                  return true;
                }, t("admin.email.portRangeNotMatch")!),
              ]}
            >
              {(field, props) => (
                <Input
                  type="number"
                  disabled={getValue(form, "enabled") === false}
                  title={t("admin.email.port")}
                  placeholder={t("admin.email.port")}
                  class="w-36"
                  icon={<span class="icon-[fluent--number-symbol-20-regular] w-5 h-5" />}
                  value={field.value}
                  error={field.error}
                  {...props}
                />
              )}
            </Field>
          </div>
          <Field
            name="sender"
            validate={[
              custom((value) => {
                if (!value && getValue(form, "enabled")) {
                  return false;
                }
                return true;
              }, t("admin.email.senderRequired")!),
            ]}
          >
            {(field, props) => (
              <Input
                class="flex-1"
                disabled={getValue(form, "enabled") === false}
                title={t("admin.email.sender")}
                placeholder={t("admin.email.sender")}
                icon={<span class="icon-[fluent--emoji-20-regular] w-5 h-5" />}
                value={field.value}
                error={field.error}
                {...props}
              />
            )}
          </Field>
          <div class="flex flex-col lg:flex-row lg:space-x-2 space-y-2 lg:space-y-0">
            <Field
              name="username"
              validate={[
                custom((value) => {
                  if (!value && getValue(form, "enabled")) {
                    return false;
                  }
                  return true;
                }, t("admin.email.usernameRequired")!),
              ]}
            >
              {(field, props) => (
                <Input
                  class="flex-1"
                  disabled={getValue(form, "enabled") === false}
                  title={t("admin.email.username")}
                  placeholder={t("admin.email.username")}
                  icon={<span class="icon-[fluent--mail-20-regular] w-5 h-5" />}
                  value={field.value}
                  error={field.error}
                  {...props}
                />
              )}
            </Field>
            <Field
              name="password"
              validate={[
                custom((value) => {
                  if (!value && getValue(form, "enabled")) {
                    return false;
                  }
                  return true;
                }, t("admin.email.passwordRequired")!),
              ]}
            >
              {(field, props) => (
                <Input
                  class="flex-1"
                  disabled={getValue(form, "enabled") === false}
                  type="password"
                  title={t("admin.email.password")}
                  placeholder={t("admin.email.password")}
                  icon={<span class="icon-[fluent--lock-20-regular] w-5 h-5" />}
                  value={field.value}
                  error={field.error}
                  {...props}
                />
              )}
            </Field>
          </div>
          <Divider direction="horizontal" />
          <Field
            name="verify_email_subject"
            validate={[
              custom((value) => {
                if (!value && getValue(form, "enabled")) {
                  return false;
                }
                return true;
              }, t("admin.email.verifyEmailSubjectRequired")!),
            ]}
          >
            {(field, props) => (
              <Input
                class="flex-1"
                disabled={getValue(form, "enabled") === false}
                title={t("admin.email.verifyEmailSubject")}
                placeholder={t("admin.email.verifyEmailSubject")}
                icon={<span class="icon-[fluent--emoji-20-regular] w-5 h-5" />}
                value={field.value ?? undefined}
                error={field.error}
                {...props}
              />
            )}
          </Field>
          <Field
            name="verify_email_body"
            validate={[
              custom((value) => {
                if (!value && getValue(form, "enabled")) {
                  return false;
                }
                return true;
              }, t("admin.email.verifyEmailBodyRequired")!),
            ]}
          >
            {(field) => (
              <Editor
                form={form}
                lineNumbers
                class="h-80"
                lang="html"
                placeholder="xHTML (RFC 2557)"
                title={t("admin.email.verifyEmailBody")}
                name="verify_email_body"
                value={field.value ?? undefined}
                error={field.error}
              />
            )}
          </Field>
          <Divider direction="horizontal" />
          <Field
            name="reset_password_email_subject"
            validate={[
              custom((value) => {
                if (!value && getValue(form, "enabled")) {
                  return false;
                }
                return true;
              }, t("admin.email.resetEmailSubjectRequired")!),
            ]}
          >
            {(field, props) => (
              <Input
                class="flex-1"
                disabled={getValue(form, "enabled") === false}
                title={t("admin.email.resetEmailSubject")}
                placeholder={t("admin.email.resetEmailSubject")}
                icon={<span class="icon-[fluent--emoji-20-regular] w-5 h-5" />}
                value={field.value ?? undefined}
                error={field.error}
                {...props}
              />
            )}
          </Field>
          <Field
            name="reset_password_email_body"
            validate={[
              custom((value) => {
                if (!value && getValue(form, "enabled")) {
                  return false;
                }
                return true;
              }, t("admin.email.resetEmailBodyRequired")!),
            ]}
          >
            {(field) => (
              <Editor
                form={form}
                lineNumbers
                class="h-80"
                lang="html"
                placeholder="xHTML (RFC 2557)"
                title={t("admin.email.resetEmailBody")}
                name="reset_password_email_body"
                value={field.value ?? undefined}
                error={field.error}
              />
            )}
          </Field>
          <Button type="submit" level="primary" class="!mt-4" loading={loading()} disabled={!config() || loading()}>
            {t("form.save")}
          </Button>
        </Form>
      </div>
    </>
  );
}

// web/src/routes/admin/platform/email/+page.svelte
<script lang="ts">
  import { platform } from '$lib/stores/platform'
  import { i18n } from '$lib/i18n'
  import RxForm from '$lib/components/RxForm.svelte'
  import { z } from 'zod'
  import { validator } from '@felte/validator-zod'
  import { createForm } from 'felte'
  import RxFormItem from '$lib/components/RxFormItem.svelte'
  import RxInput from '$lib/components/RxInput.svelte'
  import RxCheckBox from '$lib/components/RxCheckBox.svelte'
  import RxRadioGroup from '$lib/components/RxRadioGroup.svelte'
  import RxButton from '$lib/components/RxButton.svelte'
  import { getPlatformConfig, setPlatformConfig } from '$lib/api/v1/platform'
  import { onMount } from 'svelte'
  import type { Config } from '$lib/models/config'
  import { showMessage } from '$lib/stores/toast'
  import { user } from '$lib/stores/user'
  import type { AxiosError } from 'axios'
  import type { Obj } from '@felte/core'
  import { blur } from 'svelte/transition'
  import RxCodeBox from '$lib/components/RxCodeBox.svelte'

  let schema = z.object({
    enabled: z.boolean(),
    host: z
      .string()
      .trim()
      .min(1, { message: $i18n.t('init.emailHostRequired') }),
    port: z
      .number()
      .min(1, { message: $i18n.t('init.emailPortRequired') })
      .max(65535, { message: $i18n.t('init.emailPortInvalid') }),
    username: z
      .string()
      .trim()
      .email($i18n.t('init.emailInvalid'))
      .min(1, { message: $i18n.t('init.emailUsernameRequired') }),
    sender: z
      .string()
      .trim()
      .min(1, { message: $i18n.t('init.emailSenderRequired') }),
    password: z
      .string()
      .trim()
      .min(1, { message: $i18n.t('init.emailPasswordRequired') }),
    tls: z.enum(['none', 'starttls', 'tls'], {
      errorMap: () => ({ message: $i18n.t('init.tlsOptionInvalid') }),
    }),
    reset_password_email_body: z
      .string()
      .trim()
      .min(1, { message: $i18n.t('init.emailResetPasswordBodyRequired') }),
    reset_password_email_subject: z
      .string()
      .trim()
      .min(1, { message: $i18n.t('init.emailResetPasswordSubjectRequired') }),
    verify_email_body: z
      .string()
      .trim()
      .min(1, { message: $i18n.t('init.emailVerifyBodyRequired') }),
    verify_email_subject: z
      .string()
      .trim()
      .min(1, { message: $i18n.t('init.emailVerifySubjectRequired') }),
  })
  let loading = false
  let submitting = false
  let platformConfig: Config = {}
  const { form, data, touched, errors } = createForm({
    extend: validator({ schema }),
    onSubmit(values) {
      submitting = true
      const payload: Config = {
        ...platformConfig,
        email: values,
      } as Config
      setPlatformConfig(payload, $user.token)
        .then(() => {
          showMessage('success', $i18n.t('admin.config.saved'), 5000)
        })
        .catch((error) => {
          showMessage('error', `${$i18n.t('admin.config.saveFailed')}: ${(error as AxiosError).response?.data}`, 5000)
        })
        .finally(() => {
          submitting = false
        })
    },
  })
  const tlsValue = $data.tls
  $: {
    if (tlsValue !== $data.tls) {
      $touched.tls = true
    }
  }
  onMount(() => {
    loading = true
    getPlatformConfig()
      .then((res) => {
        platformConfig = res
        data.update(() => {
          return res.email as unknown as Obj
        })
      })
      .catch((error) => {
        showMessage(
          'error',
          `${$i18n.t('admin.config.platform.fetchFailed')}: ${(error as AxiosError).response?.data}`,
          5000
        )
      })
      .finally(() => {
        loading = false
      })
  })
</script>

<svelte:head><title>{$i18n.t('init.emailTitle')} - {$platform.name}</title></svelte:head>
<div class="flex-1 relative">
  <div class="flex-1 flex flex-row p-4 lg:p-6 justify-center">
    <div class="flex-1 flex flex-col max-w-5xl">
      <div class="m-2 md:m-4 flex flex-row justify-center items-center space-x-6">
        <span class="icon-[fluent--chevron-double-right-20-regular] opacity-60" />
        <h1 class="text-2xl font-bold">{$i18n.t('init.emailTitle')}</h1>
        <span class="icon-[fluent--chevron-double-left-20-regular] opacity-60" />
      </div>
      <RxForm {form}>
        <RxFormItem name="enabled" label="" hasError={$errors.enabled !== null} errors={$errors.enabled}>
          <RxCheckBox id="enabled" name="enabled" label={$i18n.t('init.emailEnabled')} />
        </RxFormItem>
        <div class="flex flex-row space-x-4">
          <RxFormItem
            name="host"
            class="flex-1"
            label={$i18n.t('init.emailHost')}
            hasError={$errors.host !== null}
            errors={$errors.host}
          >
            <RxInput
              icon="icon-[fluent--mail-20-regular]"
              class="w-full"
              id="host"
              name="host"
              hasError={$errors.host !== null}
              value={platformConfig.email?.host}
              placeholder={$i18n.t('init.emailHostPlaceholder')}
            />
          </RxFormItem>
          <RxFormItem
            class="!flex-none"
            name="port"
            label={$i18n.t('init.emailPort')}
            hasError={$errors.port !== null}
            errors={$errors.port}
          >
            <RxInput
              icon="icon-[fluent--code-20-regular]"
              class="w-full"
              id="port"
              name="port"
              hasError={$errors.port !== null}
              value={platformConfig.email?.port}
              placeholder={$i18n.t('init.emailPortPlaceholder')}
              type="number"
            />
          </RxFormItem>
        </div>
        <RxFormItem name="tls" label={$i18n.t('init.emailTls')} hasError={$errors.tls !== null} errors={$errors.tls}>
          <RxRadioGroup
            class="w-full"
            direction="row"
            items={[
              { label: $i18n.t('init.emailNoneTls'), value: 'none' },
              { label: $i18n.t('init.emailCommonTls'), value: 'tls' },
              { label: $i18n.t('init.emailStartTls'), value: 'starttls' },
            ]}
            bind:value={$data.tls}
          />
        </RxFormItem>
        <RxFormItem
          name="sender"
          class="flex-1"
          label={$i18n.t('init.emailSender')}
          hasError={$errors.sender !== null}
          errors={$errors.sender}
        >
          <RxInput
            icon="icon-[fluent--mail-20-regular]"
            class="w-full"
            id="sender"
            name="sender"
            hasError={$errors.sender !== null}
            value={platformConfig.email?.sender}
            placeholder={$i18n.t('init.emailSenderPlaceholder')}
          />
        </RxFormItem>
        <div class="flex flex-row space-x-4">
          <RxFormItem
            name="username"
            class="flex-1"
            label={$i18n.t('init.emailUsername')}
            hasError={$errors.username !== null}
            errors={$errors.username}
          >
            <RxInput
              icon="icon-[fluent--mail-20-regular]"
              class="w-full"
              id="username"
              name="username"
              hasError={$errors.username !== null}
              value={platformConfig.email?.username}
              placeholder={$i18n.t('init.emailUsernamePlaceholder')}
            />
          </RxFormItem>
          <RxFormItem
            name="password"
            class="flex-1"
            label={$i18n.t('init.emailPassword')}
            hasError={$errors.password !== null}
            errors={$errors.password}
          >
            <RxInput
              icon="icon-[fluent--lock-20-regular]"
              class="w-full"
              id="password"
              name="password"
              hasError={$errors.password !== null}
              placeholder={$i18n.t('init.emailPasswordPlaceholder')}
              value={platformConfig.email?.password}
              type="password"
            />
          </RxFormItem>
        </div>
        <div class="divider pt-12 pb-2">{$i18n.t('init.emailResetPassword')}</div>
        <RxFormItem
          name="reset_password_email_subject"
          class="flex-1"
          label={$i18n.t('init.emailResetPasswordSubject')}
          hasError={$errors.reset_password_email_subject !== null}
          errors={$errors.reset_password_email_subject}
        >
          <RxInput
            class="w-full"
            id="reset_password_email_subject"
            name="reset_password_email_subject"
            hasError={$errors.reset_password_email_subject !== null}
            value={platformConfig.email?.reset_password_email_subject}
            placeholder={$i18n.t('init.emailResetPasswordSubjectPlaceholder')}
          />
        </RxFormItem>
        <RxFormItem
          name="reset_password_email_body"
          class="flex-1"
          label={$i18n.t('init.emailResetPasswordBody')}
          hasError={$errors.reset_password_email_body !== null}
          errors={$errors.reset_password_email_body}
        >
          <RxCodeBox
            lang="html"
            name="reset_password_email_body"
            hasError={$errors.reset_password_email_body !== null}
            value={platformConfig.email?.reset_password_email_body}
            placeholder="Mode = HTML | PlainText"
          />
        </RxFormItem>
        <p class="p-1 text-sm opacity-60">{$i18n.t('init.emailTemplateRenderTips')}</p>
        <div class="divider pt-12 pb-2">{$i18n.t('init.emailVerifyEmail')}</div>
        <RxFormItem
          name="verify_email_subject"
          class="flex-1"
          label={$i18n.t('init.emailVerifyEmailSubject')}
          hasError={$errors.verify_email_subject !== null}
          errors={$errors.verify_email_subject}
        >
          <RxInput
            class="w-full"
            id="verify_email_subject"
            name="verify_email_subject"
            hasError={$errors.verify_email_subject !== null}
            value={platformConfig.email?.verify_email_subject}
            placeholder={$i18n.t('init.emailVerifyEmailSubjectPlaceholder')}
          />
        </RxFormItem>
        <RxFormItem
          name="verify_email_body"
          class="flex-1"
          label={$i18n.t('init.emailVerifyEmailBody')}
          hasError={$errors.verify_email_body !== null}
          errors={$errors.verify_email_body}
        >
          <RxCodeBox
            lang="html"
            name="verify_email_body"
            hasError={$errors.reset_password_email_body !== null}
            value={platformConfig.email?.reset_password_email_body}
            placeholder="Mode = HTML | PlainText"
          />
        </RxFormItem>
        <p class="p-1 text-sm opacity-60">{$i18n.t('init.emailTemplateRenderTips')}</p>
        <RxFormItem name="submitAction" label="">
          <RxButton class="w-full" level="primary" type="submit" loading={submitting}>
            {submitting ? $i18n.t('admin.config.updating') : $i18n.t('admin.config.update')}
          </RxButton>
        </RxFormItem>
      </RxForm>
      <div class="h-32"></div>
    </div>
  </div>
  {#if loading}
    <div
      class="absolute top-0 left-0 w-full h-full z-20 backdrop-blur flex flex-row justify-center items-center"
      transition:blur={{ amount: 20, duration: 300 }}
    >
      <span class="loading loading-spinner loading-sm" />
    </div>
  {/if}
</div>
