// web/src/routes/admin/games/[game]/teams/+page.svelte
<script lang="ts">
  import type { DTColumnAction, DTColumnsDef, DTDataEntry } from '$lib/blocks/DataTable'
  import DataTable from '$lib/blocks/DataTable.svelte'
  import { i18n } from '$lib/i18n'
  import { platform } from '$lib/stores/platform'
  import { showMessage } from '$lib/stores/toast'
  import type { AxiosError } from 'axios'
  import { admin } from '$lib/stores/admin'
  import type { Game } from '$lib/models/game'
  import { changeTeamAudit, getGameTeamList } from '$lib/api/game'
  import { State, type Team } from '$lib/models/team'
  import { getInstituteList } from '$lib/api/user'
  import { onMount } from 'svelte'
  import type { Institute } from '$lib/models/institute'
  import RxInput from '$lib/components/RxInput.svelte'
  import RxButton from '$lib/components/RxButton.svelte'
  import RxCheckBox from '$lib/components/RxCheckBox.svelte'

  let currentPage: number = 1
  let perPage: number = 15
  let total: number = 0
  let loading = false
  let teams: Team[] = []
  let filter: string = ''
  let filterNeedAudit: boolean = false

  let actions: DTColumnAction[] = [
    {
      icon: 'icon-[fluent--edit-20-regular]',
      label: '',
      level: 'info',
      type: 'link',
      href: '#{id}',
    },
    {
      icon: 'icon-[fluent--subtract-circle-20-regular]',
      label: '',
      level: 'info',
      type: 'button',
      onClick: (data: DTDataEntry) => {
        if ($admin.game !== undefined && $admin.game !== null) {
          changeTeamAudit($admin.game.id, data.id as number)
            .then(() => {
              fetchTeams()
            })
            .catch((err) => {
              showMessage('error', `${$i18n.t('team.auditFailed')}: ${(err as AxiosError).response?.data}`, 5000)
            })
        }
      },
    },
  ]

  let colDef: DTColumnsDef = {
    id: {
      header: 'ID',
      dimmed: true,
      type: 'number',
      sizePolicy: 'shrink',
      justify: 'text-center',
    },
    name: {
      header: $i18n.t('team.name'),
      type: 'plain',
      dimmed: false,
      sizePolicy: 'grow',
      justify: 'text-start',
    },
    game_id: {
      header: '',
      type: 'hidden',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-start',
    },
    token: {
      header: '',
      type: 'hidden',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-start',
    },
    state: {
      header: '',
      type: 'hidden',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-center',
    },
    institute_info: {
      header: $i18n.t('team.institute_info'),
      type: 'plain',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-center',
    },
    score: {
      header: '',
      type: 'hidden',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-center',
    },
    history: {
      header: '',
      type: 'hidden',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-center',
    },
    last_active_at: {
      header: '',
      type: 'hidden',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-center',
    },
    hidden: {
      header: '',
      type: 'bool',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-center',
    },
    banned: {
      header: '',
      type: 'bool',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-center',
    },
    needAudit: {
      header: '',
      type: 'bool',
      dimmed: false,
      sizePolicy: 'shrink',
      justify: 'text-center',
    },
  }
  let institutes: Institute[] = []
  $: renderTeams = teams.map((team) => {
    return {
      ...team,
      state: State[team.state],
      institute_info: institutes.find((i) => i.id === team.institute_id)?.name || '',
      needAudit: team.state === State.NeedAudit,
      banned: team.state === State.Banned,
      hidden: team.state === State.Hidden,
    }
  })

  function fetchTeams() {
    if (!$admin.game) return
    loading = true
    getGameTeamList($admin.game.id, currentPage, perPage, filter, filterNeedAudit)
      .then((res) => {
        teams = res.teams
        total = res.total
      })
      .catch((err) => {
        showMessage('error', `${$i18n.t('team.fetchFailed')}: ${(err as AxiosError).response?.data}`, 5000)
      })
      .finally(() => {
        loading = false
      })
  }
  // $: console.log(renderTeams)

  let storedPage: number | undefined = undefined
  let storedGameId: number | undefined = undefined

  function watchPage(p: number, g: Game | null) {
    if (p && g && (p !== storedPage || storedGameId !== g.id)) {
      fetchTeams()
      storedPage = p
      storedGameId = g.id
    }
  }

  $: watchPage(currentPage, $admin.game)

  function fetchInstitutes() {
    loading = true
    getInstituteList()
      .then((res) => {
        institutes = res
        // console.log(institutes)
      })
      .catch((err) => {
        showMessage('error', `${$i18n.t('institutes.fetchFailed')}: ${(err as AxiosError).response?.data}`, 5000)
      })
      .finally(() => {
        loading = false
      })
  }

  $: {
    if (filterNeedAudit || !filterNeedAudit) {
      fetchTeams()
    }
  }

  onMount(() => {
    fetchInstitutes()
  })
</script>

<svelte:head><title>{$i18n.t('admin.teamListSettings')} - {$platform.name}</title></svelte:head>
<div class="w-full flex-1 flex flex-col relative">
  <div class="w-full flex-1 flex flex-col px-6 lg:px-12">
    <div class="h-16 flex flex-row items-center space-x-2">
      <h2 class="text-base font-bold flex-1">{$i18n.t('admin.teamListSettings')}</h2>
      <RxCheckBox
        id="needAudit"
        name="needAudit"
        bind:checked={filterNeedAudit}
        label={$i18n.t('team.filterNeedAudit')}
      />
      <div>
        <RxInput
          size="sm"
          placeholder={$i18n.t('admin.filter')}
          icon="icon-[fluent--question-20-regular]"
          bind:value={filter}
        >
          <RxButton
            class="join-item ml-0"
            size="sm"
            on:click={() => {
              fetchTeams()
            }}
          >
            <span class="icon-[fluent--filter-20-regular] w-5 h-5"></span>
          </RxButton>
        </RxInput>
      </div>
    </div>
    <DataTable
      class="flex-1"
      {actions}
      data={renderTeams}
      {colDef}
      bind:page={currentPage}
      {total}
      {loading}
      booleanIconsDef={{
        hidden: {
          true: 'icon-[fluent--eye-off-20-regular] text-warning',
          false: '',
        },
        banned: {
          true: 'icon-[fluent--circle-off-20-regular] text-error',
          false: 'icon-[fluent--checkmark-circle-20-regular] text-success',
        },
        needAudit: {
          true: 'icon-[fluent--question-circle-20-regular] text-info',
          false: '',
        },
      }}
    />
  </div>
</div>

// web/src/routes/games/[game]/admin/teams/index.tsx
import { getTeamList } from "@api/game";
import NarrowTips from "@blocks/narrow-tips";
import { type Team, TeamState } from "@models/team";
import { A, useSearchParams } from "@solidjs/router";
import { accountStore, refreshInstitutes } from "@storage/account";
import { gameStore } from "@storage/game";
import { t } from "@storage/theme";
import { addToast } from "@storage/toast";
import Input from "@widgets/input";
import LoadingTips from "@widgets/loading-tips";
import Pagination from "@widgets/pagination";
import Select from "@widgets/select";
import Tag from "@widgets/tag";
import type { HTTPError } from "ky";
import { For, Match, Show, Switch, createEffect, createMemo, createSignal, untrack } from "solid-js";

type OrderType = "id" | "name" | "institute_id" | "state";

export default function () {
  const [searchParams, setSearchParams] = useSearchParams();
  const [teams, setTeams] = createSignal([] as Team[]);
  const page = createMemo(() => (searchParams.page && Number.parseInt(searchParams.page as string)) || 1);
  const pageSize = 15;
  const [loading, setLoading] = createSignal(false);
  const [total, setTotal] = createSignal(0);
  const filter = createMemo(() => (searchParams.filter as string) || null);
  const order = createMemo(() => (searchParams.order as string) || "id");
  const instituteId = createMemo(
    () => (searchParams.institute && Number.parseInt(searchParams.institute as string)) || null
  );

  const institutesSelect = createMemo(() => {
    return accountStore.institutes.map((i) => ({
      value: i.id.toString(),
      label: i.name,
      icon: "icon-[fluent--hat-graduation-20-regular] w-5 h-5",
    }));
  });
  refreshInstitutes();
  function refreshTeams() {
    setLoading(true);
    getTeamList(
      gameStore.current!.id,
      page(),
      pageSize,
      order() || "id",
      filter() ?? undefined,
      instituteId() ?? undefined
    )
      .then((resp) => {
        setTeams(resp[0]);
        setTotal(resp[1]);
      })
      .catch((err: HTTPError) => {
        err.response.text().then((text) => {
          addToast({
            level: "error",
            description: `${t("game.admin.teams.fetchFailed")}: ${text}`,
            duration: 5000,
          });
        });
      })
      .finally(() => setLoading(false));
  }
  createEffect(() => {
    if (page() && gameStore.current) {
      untrack(refreshTeams);
    }
  });
  return (
    <div class="w-full p-3 lg:p-6 flex flex-col flex-1 relative">
      <h3 class="h-12 flex items-center border-b border-b-layer-content/10 font-bold space-x-2">
        <span class="icon-[fluent--settings-20-regular] w-5 h-5" />
        <span class="flex-1 text-start">{t("game.admin.teams.title")}</span>
        <Select
          class="flex-1 max-w-48 min-w-0"
          size="sm"
          placeholder={t("game.admin.teams.sortBy")}
          items={[
            {
              value: "id",
              label: "ID",
              icon: "icon-[fluent--number-symbol-24-regular] w-5 h-5",
            },
            {
              value: "name",
              label: t("game.admin.teams.name")!,
              icon: "icon-[fluent--number-symbol-24-regular] w-5 h-5",
            },
            {
              value: "institute_id",
              label: t("game.admin.teams.institute")!,
              icon: "icon-[fluent--number-symbol-24-regular] w-5 h-5",
            },
            {
              value: "state",
              label: t("game.admin.teams.state")!,
              icon: "icon-[fluent--number-symbol-24-regular] w-5 h-5",
            },
          ]}
          onValueChange={(v) => {
            setSearchParams({ order: (v.value.at(0) || "id") as OrderType });
            setTimeout(refreshTeams, 100);
          }}
          value={order() ? [order()!] : undefined}
        />
        <Select
          class="flex-1 max-w-64 min-w-0"
          size="sm"
          placeholder={t("game.admin.teams.selectInstitute")}
          items={institutesSelect()}
          onValueChange={(v) => {
            setSearchParams({ institute: (v.value.at(0) && Number.parseInt(v.value.at(0)!)) || null });
            setTimeout(refreshTeams, 100);
          }}
          value={instituteId() ? [instituteId()!.toString()] : undefined}
        />
        <Input
          class="w-80"
          size="sm"
          icon={<span class="icon-[fluent--filter-16-regular] w-5 h-5" />}
          value={filter() || undefined}
          placeholder={t("game.admin.teams.filterPlaceholder")}
          onChange={(e) => {
            setSearchParams({ filter: e.target.value });
            setTimeout(refreshTeams, 100);
          }}
        />
      </h3>
      <Show when={loading()}>
        <div class="h-12 flex items-center border-b border-b-layer-content/10 font-bold space-x-4 px-2 hover:bg-layer-content/5">
          <LoadingTips />
        </div>
      </Show>
      <div class="flex-1 flex flex-col">
        <For
          each={teams()}
          fallback={
            <div class="h-12 flex items-center border-b border-b-layer-content/10 space-x-2 opacity-60">
              <span class="icon-[fluent--emoji-sad-slight-20-regular] w-5 h-5" />
              <span>{t("game.team.noExtras")}</span>
            </div>
          }
        >
          {(team) => (
            <A
              class="h-12 flex items-center border-b border-b-layer-content/10 font-bold space-x-4 px-2 hover:bg-layer-content/5 cursor-pointer"
              href={`/games/${gameStore.current?.id}/teams/${team.id}`}
            >
              <span class="icon-[fluent--flag-20-regular] w-5 h-5" />
              <span class="flex-1 truncate text-start">
                <span>{team.name}</span>
                <span class="font-normal px-2 opacity-60">#{team.id.toString(16).padStart(6, "0")}</span>
              </span>
              <Show when={team.institute_id}>
                <Tag level="info">
                  <span>{accountStore.institutes.find((v) => v.id === team.institute_id)?.name}</span>
                </Tag>
              </Show>
              <Switch>
                <Match when={team.state === TeamState.Banned}>
                  <Tag level="error">
                    <span>{t("game.admin.teams.banned")}</span>
                  </Tag>
                </Match>
                <Match when={team.state === TeamState.Pending}>
                  <Tag level="warning">
                    <span>{t("game.admin.teams.pending")}</span>
                  </Tag>
                </Match>
                <Match when={team.state === TeamState.Hidden}>
                  <Tag level="warning">
                    <span>{t("game.admin.teams.hidden")}</span>
                  </Tag>
                </Match>
              </Switch>
              <span class="font-bold opacity-60">{team.score} pts</span>
              <span class="font-normal">{team.last_active_at.toFormat("yyyy-MM-dd HH:mm:ss")}</span>
            </A>
          )}
        </For>
      </div>
      <Pagination
        class="p-6 lg:p-9"
        count={total()}
        pageSize={pageSize}
        page={page()}
        onPageChange={(page) => setSearchParams({ page: page.page })}
      />

      <NarrowTips breakpoint="lg" />
    </div>
  );
}
